#include <Arduino.h>
#include "Keyboard.h"

const char key_bindings[][16] PROGMEM =
    {
        "KEY_LEFT_CTRL",
        "KEY_LEFT_SHIFT",
        "KEY_LEFT_ALT",
        "KEY_LEFT_GUI",
        "KEY_RIGHT_CTRL",
        "KEY_RIGHT_SHIFT",
        "KEY_RIGHT_ALT",
        "KEY_RIGHT_GUI",
        "KEY_UP_ARROW",
        "KEY_DOWN_ARROW",
        "KEY_LEFT_ARROW",
        "KEY_RIGHT_ARROW",
        "KEY_BACKSPACE",
        "KEY_TAB",
        "KEY_RETURN",
        "KEY_ESC",
        "KEY_INSERT",
        "KEY_DELETE",
        "KEY_PAGE_UP",
        "KEY_PAGE_DOWN",
        "KEY_HOME",
        "KEY_END",
        "KEY_CAPS_LOCK",
        "KEY_F1",
        "KEY_F2",
        "KEY_F3",
        "KEY_F4",
        "KEY_F5",
        "KEY_F6",
        "KEY_F7",
        "KEY_F8",
        "KEY_F9",
        "KEY_F10",
        "KEY_F11",
        "KEY_F12",
        "KEY_F13",
        "KEY_F14",
        "KEY_F15",
        "KEY_F16",
        "KEY_F17",
        "KEY_F18",
        "KEY_F19",
        "KEY_F20",
        "KEY_F21",
        "KEY_F22",
        "KEY_F23",
        "KEY_F24"};

const int key_codes[] PROGMEM =
    {
        KEY_LEFT_CTRL,
        KEY_LEFT_SHIFT,
        KEY_LEFT_ALT,
        KEY_LEFT_GUI,
        KEY_RIGHT_CTRL,
        KEY_RIGHT_SHIFT,
        KEY_RIGHT_ALT,
        KEY_RIGHT_GUI,
        KEY_UP_ARROW,
        KEY_DOWN_ARROW,
        KEY_LEFT_ARROW,
        KEY_RIGHT_ARROW,
        KEY_BACKSPACE,
        KEY_TAB,
        KEY_RETURN,
        KEY_ESC,
        KEY_INSERT,
        KEY_DELETE,
        KEY_PAGE_UP,
        KEY_PAGE_DOWN,
        KEY_HOME,
        KEY_END,
        KEY_CAPS_LOCK,
        KEY_F1,
        KEY_F2,
        KEY_F3,
        KEY_F4,
        KEY_F5,
        KEY_F6,
        KEY_F7,
        KEY_F8,
        KEY_F9,
        KEY_F10,
        KEY_F11,
        KEY_F12,
        KEY_F13,
        KEY_F14,
        KEY_F15,
        KEY_F16,
        KEY_F17,
        KEY_F18,
        KEY_F19,
        KEY_F20,
        KEY_F21,
        KEY_F22,
        KEY_F23,
        KEY_F24};

int find_key(char *word)
{
    for (int i = 0; i < 47; i++)
    {
        if (strcmp(key_bindings[i], word) == 0)
            return key_codes[i];
    }
    return -1;
}
